version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  redis:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - 6379:6379


#  springboot-internal-api:
#    container_name: springboot-internal-api
#    build: ./push-internal-api/dockerfile
#    restart: always
#    ports:
#      - "${PORT}:8080"
#    depends_on:
#      - mysql
#    environment:
#      WAIT_HOSTS: mysql:3306
#      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
#    env_file: ./.env
#
#  springboot-batch:
#    container_name: springboot-batch
#    build: ./push-internal-api/dockerfile
#    restart: always
#    ports:
#      - "${PORT}:8080"
#    depends_on:
#      - mysql
#    environment:
#      WAIT_HOSTS: mysql:3306
#      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
#    env_file: ./.env



